//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enumeration
    {
        public int Enum_UID { get; set; }
        public string Enum_Type { get; set; }
        public string Enum_Name { get; set; }
        public string Enum_Value { get; set; }
        public string Decription { get; set; }
    }
}
