//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowChart_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlowChart_Detail()
        {
            this.FlowChart_MgData_Temp = new HashSet<FlowChart_MgData_Temp>();
            this.FlowChart_MgData = new HashSet<FlowChart_MgData>();
        }
    
        public int FlowChart_Detail_UID { get; set; }
        public int FlowChart_Master_UID { get; set; }
        public int System_FunPlant_UID { get; set; }
        public int Process_Seq { get; set; }
        public string DRI { get; set; }
        public string Place { get; set; }
        public string Process { get; set; }
        public int Product_Stage { get; set; }
        public string Color { get; set; }
        public string Process_Desc { get; set; }
        public string Material_No { get; set; }
        public int FlowChart_Version { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string FlowChart_Version_Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_MgData_Temp> FlowChart_MgData_Temp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowChart_MgData> FlowChart_MgData { get; set; }
        public virtual System_Function_Plant System_Function_Plant { get; set; }
        public virtual FlowChart_Master FlowChart_Master { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
