//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowChart_MgData
    {
        public int FlowChart_MgData_UID { get; set; }
        public int FlowChart_Detail_UID { get; set; }
        public int Product_Plan { get; set; }
        public double Target_Yield { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public System.DateTime Product_Date { get; set; }
    
        public virtual FlowChart_Detail FlowChart_Detail { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
