//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Role_FunctionSub
    {
        public int System_Role_FunctionSub_UID { get; set; }
        public int System_Role_Function_UID { get; set; }
        public int System_FunctionSub_UID { get; set; }
        public bool Sub_Flag { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual System_FunctionSub System_FunctionSub { get; set; }
        public virtual System_Role_Function System_Role_Function { get; set; }
        public virtual System_Users System_Users { get; set; }
    }
}
