//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Plant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_Plant()
        {
            this.System_Function_Plant = new HashSet<System_Function_Plant>();
            this.System_User_Plant = new HashSet<System_User_Plant>();
        }
    
        public int System_Plant_UID { get; set; }
        public string CCODE { get; set; }
        public string Plant { get; set; }
        public string Location { get; set; }
        public string Type { get; set; }
        public string Name_0 { get; set; }
        public string Name_1 { get; set; }
        public string PlantManager_Name { get; set; }
        public string PlantManager_Tel { get; set; }
        public string PlantManager_Email { get; set; }
        public string Name_2 { get; set; }
        public string Legal_Entity_EN { get; set; }
        public string Legal_Entity_ZH { get; set; }
        public string Address_EN { get; set; }
        public string Address_ZH { get; set; }
        public string Coordinate { get; set; }
        public System.DateTime Begin_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Function_Plant> System_Function_Plant { get; set; }
        public virtual System_Users System_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_User_Plant> System_User_Plant { get; set; }
    }
}
