//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Function
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_Function()
        {
            this.System_FunctionSub = new HashSet<System_FunctionSub>();
            this.System_Role_Function = new HashSet<System_Role_Function>();
        }
    
        public int Function_UID { get; set; }
        public Nullable<int> Parent_Function_UID { get; set; }
        public string Function_ID { get; set; }
        public string Function_Name { get; set; }
        public string Function_Desc { get; set; }
        public int Order_Index { get; set; }
        public string Icon_ClassName { get; set; }
        public string URL { get; set; }
        public bool Is_Show { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
        public string Mobile_URL { get; set; }
    
        public virtual System_Users System_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_FunctionSub> System_FunctionSub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<System_Role_Function> System_Role_Function { get; set; }
    }
}
