//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIP_Change_History
    {
        public int Change_UID { get; set; }
        public string Change_Type { get; set; }
        public int Product_UID { get; set; }
        public Nullable<int> WIP_Old { get; set; }
        public Nullable<int> WIP_Add { get; set; }
        public string Comment { get; set; }
        public int Modified_UID { get; set; }
        public System.DateTime Modified_Date { get; set; }
    
        public virtual System_Users System_Users { get; set; }
    }
}
